# stage 1 building the code
FROM alpine:3.11.3 as builder
ARG VERSION
WORKDIR /home/weave
RUN apk add --no-cache bash conntrack-tools iproute2 util-linux curl go libpcap-dev file
COPY / /scope
WORKDIR /scope
RUN time env GOGC=off CGO_ENABLED=1  go build -mod vendor -ldflags "-extldflags \"-static\" -X main.version="${VERSION}" -s -w" -tags 'netgo unsafe' -o scope ./prog

# stage 2 
FROM alpine:3.11.3
WORKDIR /home/weave
RUN apk add --no-cache bash conntrack-tools iproute2 util-linux curl file
COPY --from=builder /scope/scope /home/weave/
RUN file /home/weave/scope
ENTRYPOINT ["/home/weave/scope", "--mode=probe", "--no-app", "--probe.docker=true"]

ARG revision
LABEL works.weave.role="system" \
      maintainer="Weaveworks <help@weave.works>" \
      org.opencontainers.image.title="cloud-agent" \
      org.opencontainers.image.source="https://github.com/weaveworks/scope" \
      org.opencontainers.image.revision="${revision}" \
      org.opencontainers.image.vendor="Weaveworks"
